# Development Configuration
# For local development, hardcoded values are used
# For Netlify builds, these will be replaced with environment variables

auth0:
  domain: "dev-l57dcpkhob0u7ykb.us.auth0.com"
  client_id: "Dq4tBsHjgcIGbXkVU8PPvjAq3WYmnSBC"
  audience: "https://carsontkempf.github.io/api/carsons-meditations"

spotify:
  client_id: "80826ef3daa547f49d843c254ad224b6"

apple_music:
  team_id: "5S855HB895"
  key_id: "T5ZX676QRQ"
  developer_token: "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlQ1Wlg2NzZRUlEifQ.eyJpYXQiOjE3NjgzNTUxNzUsImV4cCI6MTc4MzkwNzE3NSwiaXNzIjoiNVM4NTVIQjg5NSJ9.0jmfs0ZKeSx_ARzqIJnOeoaucjH0U16WTuqd9N1K6ZGLAZZimyF4ebXB-aOgvM8BuP08w0SItlhBjW8kQdZGiw"