[build]
  command = "bundle install && JEKYLL_ENV=production bundle exec jekyll build --config _config.yml,_config-prod.yml"
  publish = "_site"

[functions]
  directory = "netlify/functions"

# Production context uses production environment variables
[context.production]
  command = "bundle install && JEKYLL_ENV=production bundle exec jekyll build --config _config.yml,_config-prod.yml"

# Branch deploys use dev environment variables
[context.branch-deploy]
  command = "bundle install && JEKYLL_ENV=production bundle exec jekyll build --config _config.yml,_config-dev.yml"

# Deploy previews use dev environment variables
[context.deploy-preview]
  command = "bundle install && JEKYLL_ENV=production bundle exec jekyll build --config _config.yml,_config-dev.yml"
